In [3]:
import numpy as np
import pandas as pd

In [3]:
array = np.arange(0,20).reshape((5,4))
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [9]:
data = pd.DataFrame(array,index=["row1","row2","row3","row4","row5"],columns=["col1","col2","col3","col4"])
print(data)


      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


In [10]:
print(data.head())

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


In [13]:
print(data.tail())

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


In [14]:
type(data)

pandas.core.frame.DataFrame

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int64
 1   col2    5 non-null      int64
 2   col3    5 non-null      int64
 3   col4    5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [16]:
print(data.describe())

            col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000


In [5]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [6]:
arr2 = np.arange(20,200,20)

In [7]:
print(arr2)

[ 20  40  60  80 100 120 140 160 180]


In [9]:
arr2 = arr2.reshape((3,3))
print(arr2)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]


In [12]:
#let's form a data frame from arr2
df2 = pd.DataFrame(arr2,index=["Row1","Row2","Row3"],columns=["Column1","Column2","Column3"])
print(df2)

      Column1  Column2  Column3
Row1       20       40       60
Row2       80      100      120
Row3      140      160      180


In [14]:
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))

[240 300 360]
[120 300 480]


In [16]:
print(df2)

      Column1  Column2  Column3
Row1       20       40       60
Row2       80      100      120
Row3      140      160      180


In [21]:
print(df2[["Column1","Column2",]])

      Column1  Column2
Row1       20       40
Row2       80      100
Row3      140      160


In [22]:
print(df2[["Column1"]])

      Column1
Row1       20
Row2       80
Row3      140


In [24]:
print(print(df2['Column1']))

Row1     20
Row2     80
Row3    140
Name: Column1, dtype: int64
None


In [25]:
print(type(df2['Column1']))

<class 'pandas.core.series.Series'>


In [27]:
#using row index name (loc)
print(df2.loc[["Row1","Row2"]])

      Column1  Column2  Column3
Row1       20       40       60
Row2       80      100      120


In [28]:
print(df2)

      Column1  Column2  Column3
Row1       20       40       60
Row2       80      100      120
Row3      140      160      180


In [29]:
print(df2.iloc[0:2,0:2])

      Column1  Column2
Row1       20       40
Row2       80      100


In [30]:
print(arr2)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]


In [35]:
print(pd.__version__)

2.2.3


In [36]:
print(df2)

      Column1  Column2  Column3
Row1       20       40       60
Row2       80      100      120
Row3      140      160      180


In [37]:
df2.loc[4] = [200,220,240]

In [38]:
print(df2)

      Column1  Column2  Column3
Row1       20       40       60
Row2       80      100      120
Row3      140      160      180
4         200      220      240


In [39]:
df2.loc["Row4"] = [200,220,240]

In [40]:
print(df2)

      Column1  Column2  Column3
Row1       20       40       60
Row2       80      100      120
Row3      140      160      180
4         200      220      240
Row4      200      220      240


In [41]:
df2 = df2.drop(4)

In [42]:
print(df2)

      Column1  Column2  Column3
Row1       20       40       60
Row2       80      100      120
Row3      140      160      180
Row4      200      220      240


In [62]:
print(df2.iloc[0:4,0:1]),print(df2.iloc[0:4,2:4])

      Column1
Row1       20
Row2       80
Row3      140
Row4      200
      Column3
Row1       60
Row2      120
Row3      180
Row4      240


(None, None)

In [70]:
print(df2[["Column1","Column3"]])

      Column1  Column3
Row1       20       60
Row2       80      120
Row3      140      180
Row4      200      240


In [71]:
print(df2.values)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]
 [200 220 240]]


In [72]:
print(df2.iloc[0:1:2])


      Column1  Column2  Column3
Row1       20       40       60


In [73]:
print(df2.iloc[2:2:2])

Empty DataFrame
Columns: [Column1, Column2, Column3]
Index: []
